### PR TITLE
[FEATURE] Section on localizing inline elements

### PR DESCRIPTION
**Pull request by mabolek**
Relying heavily on @spoonerWeb's answer on StackOverflow: https://stackoverflow.com/questions/46566124/typo3-localize-all-records-and-synchronize-with-original-language#answer-46582053

### CODE REVIEW

**Comment by susannemoog** [comment]
@linawolf with your screenshot experience: can you take a look at the screenshot? is that using the "correct" number graphics?

**Comment by linawolf** [comment]
@mabolek please change the Grafic elements (numbers) in your screenshot to adhere to the Guidelines for Images with grafic elements. https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/GuidelinesForImages.html#guidelines-for-screenshots-with-graphics-elements

**Comment by mabolek** [comment]
@linawolf OK. I don't have the original screenshot (it was from an internal support request), but I'll see if I can conjure up a new one.

**Comment by flicstar** [comment]
@mabolek PING it's our sweeping week, and we're chasing up open PRs. Are you able to conjure up a new screenshot as per your comment from 23 July? Thanks!

**Comment by linawolf** [comment]
Let's merge this for now. We didn't start working on automating the Localization Guide Screenshots yet. Once we get there, we will also automate this one.

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Releases: master, 11.5

**Pull request merged**
